name: Automatizar boas-vindas em Issues
on:
  issues:
    types: [opened]
jobs:
  comentar:
    runs-on: ubuntu-latest
    steps:
      - name: Executar GitHub Script
        uses: actions/github-script@v6
        with:
          script: |-
            const repoOwner = context.repo.owner;
            const repoRepo = context.repo.repo;
            const issueNumber = context.payload.issue.number;

            console.log(`Interagindo com a issue #${issueNumber}`);

            await github.rest.issues.createComment({
              owner: repoOwner,
              repo: repoRepo,
              issue_number: issueNumber,
              body: 'Olá! Obrigado por abrir uma issue. Nossa equipe irá analisar em breve!'
            });
